# Generated by Django 4.1.5 on 2023-01-29 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_delete_projectlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_users',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.projects'),
        ),
    ]
